# Generated by Django 5.1.3 on 2024-12-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='static/default/default.png', null=True, upload_to='static/post_images/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, default='static/default/default.png', null=True, upload_to='static/school_images/'),
        ),
    ]
