# Generated by Django 4.2.19 on 2025-03-09 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_alter_post_image_alter_school_image_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tours_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
