# Generated by Django 5.1.3 on 2024-11-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_points_profile_grade_profile_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture.', null=True, upload_to='static/profile_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, help_text="Applicable for students. Example: '10'", max_length=50, null=True),
        ),
    ]
