# Generated by Django 5.1.3 on 2024-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profile_picture_alter_profile_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/profile_images/default_pfp', help_text='Upload a profile picture.', null=True, upload_to='static/profile_images/'),
        ),
    ]
