# Generated by Django 4.2.19 on 2025-03-09 10:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dmsakestc/image/upload/v1740333445/Default_pfp.svg_gavlli.png', max_length=255, null=True, verbose_name='profile_picture_image'),
        ),
    ]
