# Generated by Django 4.2.19 on 2025-03-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_appuser_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='userId',
        ),
    ]
